# frozen_string_literal: true

require_relative "claude_hooks/version"
require_relative "claude_hooks/configuration"
require_relative "claude_hooks/logger"
require_relative "claude_hooks/base"
require_relative "claude_hooks/cli"

# Hook classes
require_relative "claude_hooks/user_prompt_submit"
require_relative "claude_hooks/pre_tool_use"
require_relative "claude_hooks/permission_request"
require_relative "claude_hooks/post_tool_use"
require_relative "claude_hooks/notification"
require_relative "claude_hooks/message_display"
require_relative "claude_hooks/stop"
require_relative "claude_hooks/subagent_stop"
require_relative "claude_hooks/pre_compact"
require_relative "claude_hooks/session_start"
require_relative "claude_hooks/session_end"
require_relative "claude_hooks/setup"
require_relative "claude_hooks/subagent_start"
require_relative "claude_hooks/user_prompt_expansion"
require_relative "claude_hooks/post_tool_batch"
require_relative "claude_hooks/config_change"
require_relative "claude_hooks/task_created"
require_relative "claude_hooks/task_completed"
require_relative "claude_hooks/teammate_idle"
require_relative "claude_hooks/post_tool_use_failure"
require_relative "claude_hooks/stop_failure"
require_relative "claude_hooks/post_compact"
require_relative "claude_hooks/cwd_changed"
require_relative "claude_hooks/file_changed"
require_relative "claude_hooks/instructions_loaded"
require_relative "claude_hooks/worktree_remove"
require_relative "claude_hooks/permission_denied"
require_relative "claude_hooks/elicitation"
require_relative "claude_hooks/elicitation_result"
require_relative "claude_hooks/worktree_create"

# Output classes
require_relative "claude_hooks/output/base"
require_relative "claude_hooks/output/user_prompt_submit"
require_relative "claude_hooks/output/pre_tool_use"
require_relative "claude_hooks/output/permission_request"
require_relative "claude_hooks/output/post_tool_use"
require_relative "claude_hooks/output/notification"
require_relative "claude_hooks/output/message_display"
require_relative "claude_hooks/output/stop"
require_relative "claude_hooks/output/subagent_stop"
require_relative "claude_hooks/output/pre_compact"
require_relative "claude_hooks/output/session_start"
require_relative "claude_hooks/output/session_end"
require_relative "claude_hooks/output/setup"
require_relative "claude_hooks/output/subagent_start"
require_relative "claude_hooks/output/user_prompt_expansion"
require_relative "claude_hooks/output/post_tool_batch"
require_relative "claude_hooks/output/config_change"
require_relative "claude_hooks/output/task_created"
require_relative "claude_hooks/output/task_completed"
require_relative "claude_hooks/output/teammate_idle"
require_relative "claude_hooks/output/post_tool_use_failure"
require_relative "claude_hooks/output/stop_failure"
require_relative "claude_hooks/output/post_compact"
require_relative "claude_hooks/output/cwd_changed"
require_relative "claude_hooks/output/file_changed"
require_relative "claude_hooks/output/instructions_loaded"
require_relative "claude_hooks/output/worktree_remove"
require_relative "claude_hooks/output/permission_denied"
require_relative "claude_hooks/output/elicitation"
require_relative "claude_hooks/output/elicitation_result"
require_relative "claude_hooks/output/worktree_create"

module ClaudeHooks
  class Error < StandardError; end
end